services:
  - name: pspml
    type: native
    runtime: python
    repo: https://github.com/JunnieYAHH/PSPML  # Change this!
    branch: master  # Change if using a different branch
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5001 app:app
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://gerelitopuyos:gerelitopuyos@atlascluster.7cyczkf.mongodb.net/PSPData?retryWrites=true&w=majority"
      - key: PORT
        value: "5001"